In [1]:
import numpy as np  
import random

class Matrix:
    def __init__(self, nrows, ncols):
        self.matrix = np.array([[0 for x in range(ncols)] for y in range(nrows)])
        
    def rand(self):
        self.matrix = np.array([[random.uniform(1, 100) for x in range(self.matrix.shape[1])] for y in range(self.matrix.shape[0])])
     
    def multiply(self, n):
        # matrix product
        if isinstance(n, Matrix):
            if(self.matrix.shape[1] == n.matrix.shape[0]):
                result = Matrix(self.matrix.shape[0], n.matrix.shape[1])
                
                for i in range(self.matrix.shape[0]):
                    for j in range(self.matrix.shape[0]):
                        sum = 0
                        for k in range(self.matrix.shape[1]):
                            sum += self.matrix[i][k]*n.matrix[k][j]
                            
                        result.matrix[i][j] = sum 
            return result
           
        # scalar product
        else:
            for i in range(self.matrix.shape[0]):
                for j in range(self.matrix.shape[1]):
                    self.matrix[i][j] *= n
                
    def add(self, n):
        if isinstance(n, Matrix):
            for i in range(self.matrix.shape[0]):
                for j in range(self.matrix.shape[1]):
                    self.matrix[i][j] += n.matrix[i][j]
           
        else:
            for i in range(self.matrix.shape[0]):
                for j in range(self.matrix.shape[1]):
                    self.matrix[i][j] += n
                
    def change(self, nrow, ncol, val):
        self.matrix[nrow][ncol] = val
                
    def print(self):
        print(self.matrix)
        
    
    def t(self):
        res = Matrix(self.matrix.shape[1], self.matrix.shape[0])
        for i in range(self.matrix.shape[0]):
            for j in range(self.matrix.shape[1]):
                res.matrix[j][i] = self.matrix[i][j]
                
        return res

In [2]:
m1 = Matrix(2,3)
m2 = Matrix(3,2)
m1.change(0,0,6)
m1.change(0,1,7)
m1.change(0,2,0)
m1.change(1,0,7)
m1.change(1,1,2)
m1.change(1,2,6)
m1.print()

[[6 7 0]
 [7 2 6]]


In [3]:
m2.change(0,0,5)
m2.change(0,1,3)
m2.change(1,0,1)
m2.change(1,1,1)
m2.change(2,0,5)
m2.change(2,1,1)
m2.print()

[[5 3]
 [1 1]
 [5 1]]


In [4]:
res = m2.t()
res.print()

[[5 1 5]
 [3 1 1]]
